In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [3]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [4]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b

In [6]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [9]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22655.951 
Prediction:
 [[22.048063]
 [21.619787]
 [24.096693]
 [22.293005]
 [18.633902]]
100 Cost:  5.6471696 
Prediction:
 [[155.50876]
 [182.17552]
 [182.21854]
 [194.49936]
 [141.12082]]
200 Cost:  5.449226 
Prediction:
 [[155.4331 ]
 [182.22672]
 [182.19452]
 [194.48853]
 [141.18248]]
300 Cost:  5.2612543 
Prediction:
 [[155.35939]
 [182.27655]
 [182.17105]
 [194.47812]
 [141.24237]]
400 Cost:  5.082733 
Prediction:
 [[155.28761]
 [182.32515]
 [182.14821]
 [194.46817]
 [141.30061]]
500 Cost:  4.9132347 
Prediction:
 [[155.21765]
 [182.37245]
 [182.12596]
 [194.45859]
 [141.35718]]
600 Cost:  4.752207 
Prediction:
 [[155.14948]
 [182.41852]
 [182.10422]
 [194.44936]
 [141.41216]]
700 Cost:  4.5992475 
Prediction:
 [[155.08305]
 [182.4634 ]
 [182.08305]
 [194.44054]
 [141.46558]]
800 Cost:  4.453902 
Prediction:
 [[155.01836]
 [182.50711]
 [182.06236]
 [194.43208]
 [141.51747]]
900 Cost:  4.315825 
Prediction:
 [[154.95529]
 [182.54967]
 [182.04219]
 [194.42393]
 [141.56789