In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

In [2]:
xy = np.loadtxt('../data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, -1]

In [3]:
y_data

array([152., 185., 180., 196., 142., 101., 149., 115., 175., 164., 141.,
       141., 184., 152., 148., 192., 147., 183., 177., 159., 177., 175.,
       175., 149., 192.], dtype=float32)

In [4]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25,) [152. 185. 180. 196. 142. 101. 149. 115. 175. 164. 141. 141. 184. 152.
 148. 192. 147. 183. 177. 159. 177. 175. 175. 149. 192.]


In [5]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None])

In [6]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [7]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b

In [8]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [9]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-6)
train = optimizer.minimize(cost)

In [10]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [11]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X:x_data, Y:y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  21178.72 
Prediction:
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]
 [12.33103  ]
 [ 3.150511 ]
 [14.347944 ]
 [ 4.2534237]
 [14.485708 ]
 [10.678068 ]
 [28.80464  ]
 [29.298803 ]
 [11.237837 ]
 [18.646544 ]
 [31.189451 ]
 [13.344664 ]
 [28.841742 ]
 [25.66281  ]
 [15.084761 ]
 [16.798368 ]
 [15.924551 ]
 [31.36112  ]
 [24.986364 ]]
100 Cost:  1197.2592 
Prediction:
 [[152.50412]
 [178.46059]
 [178.60936]
 [190.59404]
 [138.24118]
 [ 95.49265]
 [138.33516]
 [ 96.59574]
 [160.96794]
 [140.11873]
 [135.87178]
 [130.39668]
 [188.41264]
 [161.947  ]
 [137.83061]
 [177.82285]
 [157.50291]
 [164.56725]
 [180.9943 ]
 [161.80284]
 [162.84196]
 [163.95775]
 [156.7885 ]
 [162.83385]
 [187.51483]]
200 Cost:  1189.4792 
Prediction:
 [[154.86502]
 [181.34242]
 [181.42395]
 [193.68443]
 [140.42949]
 [ 97.15013]
 [140.67351]
 [ 98.36293]
 [163.70226]
 [142.71089]
 [138.1121 ]
 [132.6349 ]
 [191.29552]
 [164.31065]
 [140.1891 ]
 [180.76706]
 [159.73729]


In [12]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Ohter scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[165.94743]]
Ohter scores will be  [[109.42674]
 [197.56024]]
