In [54]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

In [55]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, -1]

In [56]:
y_data

array([152., 185., 180., 196., 142., 101., 149., 115., 175., 164., 141.,
       141., 184., 152., 148., 192., 147., 183., 177., 159., 177., 175.,
       175., 149., 192.], dtype=float32)

In [57]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25,) [152. 185. 180. 196. 142. 101. 149. 115. 175. 164. 141. 141. 184. 152.
 148. 192. 147. 183. 177. 159. 177. 175. 175. 149. 192.]


In [58]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None])

In [59]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [60]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b

In [61]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [62]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-6)
train = optimizer.minimize(cost)

In [63]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [64]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X:x_data, Y:y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  51948.98 
Prediction:
 [[-67.36589 ]
 [-65.96739 ]
 [-72.587906]
 [-81.164536]
 [-44.768494]
 [-34.371243]
 [-67.9982  ]
 [-61.012886]
 [-60.678894]
 [-59.435112]
 [-58.86882 ]
 [-52.191437]
 [-72.58837 ]
 [-56.271255]
 [-66.29223 ]
 [-70.32872 ]
 [-46.362137]
 [-86.484406]
 [-71.17541 ]
 [-65.66039 ]
 [-76.89191 ]
 [-64.870575]
 [-73.97633 ]
 [-62.428658]
 [-69.752815]]
100 Cost:  1193.2255 
Prediction:
 [[140.61572 ]
 [183.98181 ]
 [173.70303 ]
 [187.07916 ]
 [145.84058 ]
 [106.176254]
 [132.8201  ]
 [ 87.90212 ]
 [172.92798 ]
 [156.97096 ]
 [134.58704 ]
 [138.55438 ]
 [181.84909 ]
 [155.21873 ]
 [135.44693 ]
 [183.32686 ]
 [155.02913 ]
 [154.53195 ]
 [171.39603 ]
 [151.38863 ]
 [158.59058 ]
 [169.63089 ]
 [150.53578 ]
 [147.23166 ]
 [189.28784 ]]
200 Cost:  1175.5117 
Prediction:
 [[144.4371 ]
 [188.54886]
 [178.2151 ]
 [192.00752]
 [149.30556]
 [108.75028]
 [136.53801]
 [ 90.69939]
 [177.20793]
 [160.96487]
 [138.14659]
 [142.05835]
 [186.4954 ]
 [159.05887]
 [139.17966]
 

In [65]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Ohter scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[209.82556]]
Ohter scores will be  [[117.764366]
 [177.77219 ]]
