In [12]:
import tensorflow as tf
tf.set_random_seed(777) # for reproducibility

In [13]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [14]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [15]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [16]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [17]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis -  Y))

In [18]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [19]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [20]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y:y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  11366.697 
Prediction:
 [63.399445 66.89691  71.169106 72.95558  52.27266 ]
100 Cost:  14.44982 
Prediction:
 [157.79507 180.61832 183.08237 194.84927 139.06029]
200 Cost:  13.798487 
Prediction:
 [157.65802 180.7116  183.03949 194.82513 139.17688]
300 Cost:  13.181091 
Prediction:
 [157.52455 180.80237 182.99771 194.8018  139.29025]
400 Cost:  12.595747 
Prediction:
 [157.39458 180.89078 182.957   194.77919 139.40051]
500 Cost:  12.040855 
Prediction:
 [157.26802 180.97687 182.91736 194.75734 139.50772]
600 Cost:  11.514662 
Prediction:
 [157.14474 181.06068 182.8787  194.73619 139.61198]
700 Cost:  11.015831 
Prediction:
 [157.02472 181.1423  182.84103 194.71573 139.71336]
800 Cost:  10.542796 
Prediction:
 [156.9078  181.22177 182.80432 194.69597 139.81192]
900 Cost:  10.094267 
Prediction:
 [156.79393 181.29913 182.76855 194.67685 139.90775]
1000 Cost:  9.668946 
Prediction:
 [156.68306 181.37448 182.7337  194.6584  140.00093]
1100 Cost:  9.265625 
Prediction:
 [156.57506 